<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHNr5vyR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHNr5vyR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHNr5vyR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHNr5vyR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHNr5vyR\App_KernelDevDebugContainer([
    'container.build_hash' => 'HNr5vyR',
    'container.build_id' => 'fe691dd6',
    'container.build_time' => 1620365247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHNr5vyR');
