<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsDIatK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsDIatK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsDIatK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsDIatK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMsDIatK\App_KernelDevDebugContainer([
    'container.build_hash' => 'MsDIatK',
    'container.build_id' => 'b387108f',
    'container.build_time' => 1620206573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsDIatK');
