<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1Xlphs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1Xlphs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY1Xlphs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY1Xlphs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY1Xlphs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y1Xlphs',
    'container.build_id' => '3d566522',
    'container.build_time' => 1620538891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1Xlphs');
